version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: course_username
      POSTGRES_PASSWORD: course_password
      POSTGRES_DB: course_database
    ports:
      - "5432:5432"
    expose:
      - 5432
