###

# curl --location --request POST 'http://localhost:8080/course'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "id": "97fa5af4-bd81-45d5-974f-d5a3970af252",
#    "name": "Test 1"
#}'
POST http://localhost:8080/course
Content-Type: application/json

{
  "id": "97fa5af4-bd81-45d5-974f-d5a3970af252",
  "name": "Test 1"
}

###

